### PR TITLE
remove default templates

### PR DESCRIPTION
**Pull request by kevinpapst**
This is a rather drastic refactor approach, which prevents multiple issues and allows to use this bundle with "all" templates.

1. Moves the configuration to the "invoice section", so it can be easier found by everyone
2. Uses an event approach to inject the payment terms 

Edit: [Fixed with release 1.23.1](https://github.com/kevinpapst/kimai2/releases/tag/1.23.1):
~~Unfortunately this currently cannot be used, because Kimai uses [Deferred Implicit change tracking](https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/change-tracking-policies.html#deferred-implicit) and when saving the invoice, the template is persisted with the new payment terms. I will change this behavior likely with the next release.~~  

For now I wanted to share the changes as "inspiration" 😄

### CODE REVIEW

**Comment by LiaraAlis** [comment]
Thank you for the PR!
I was not sure if it is okay to inject configuration in the default system sections. Because of that, I created a new section.
I really like to move the option to the invoice section.

About the second change: To be honest, I'm not sure if I understand it correctly. You mean, with this change the payment terms are changed in database after saving an invoice?
I like the idea but I'm not sure if this is safe for use. Maybe it is easier to add an block before the payment terms in the default terms?

**Comment by kevinpapst** [comment]
I wanted to make the PR a draft for the latter reason, but couldn't for some reason.
Anyway: I just pushed a fix for the issue. See the problem is that Doctrine automatically saves all pending changes on all managed objects. That is convenient in 99,9% of all cases. But here it leads to a bug.

> You mean, with this change the payment terms are changed in database after saving an invoice?

Yes, which is definitely NOT wanted.
But what is not wanted as well IMO is that you have to overwrite the default templates. 
How do you make sure that changes from Kimai are synced to your plugin? And what if someone uses a custom template?

That is why I adapted the code to dynamically inject the text into the payment terms. 
And with https://github.com/kevinpapst/kimai2/pull/3493 they will not get persisted any longer.

**Comment by LiaraAlis** [comment]
> But what is not wanted as well IMO is that you have to overwrite the default templates.

Agree.

> How do you make sure that changes from Kimai are synced to your plugin? And what if someone uses a custom template?

I don't want to copy the templates. This is only the case for the current version because there is no other elegant way for this. After merging PR https://github.com/kevinpapst/kimai2/pull/3484 I would replace that.

For custom templates, there is a note in the [README.md](https://github.com/LiaraAlis/kimai2-SmallBusinessRuleBundle/blob/7aa88ee93b87916fac382deeebfbefb6b9afca6c/README.md).

> That is why I adapted the code to dynamically inject the text into the payment terms.
And with https://github.com/kevinpapst/kimai2/pull/3493 they will not get persisted any longer.

Do you think this is better than adding blocks in the default templates? Of course, this change would work even with custom templates without the need to adjust them.

**Comment by kevinpapst** [comment]
> Do you think this is better than adding blocks in the default templates? Of course, this change would work even with custom templates without the need to adjust them.

Exactly. This way we would cover a much broader user base without the need of changing anything in core (besides that tax exclude).

**Comment by kevinpapst** [comment]
Latest release includes the workaround which would allow to apply this PR.

But please check and test it first - at the end it is only my idea but your plugin 😄

**Pull request merged**
